services:
  - type: web
    name: monprojet-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn monprojet.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "monprojet.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: pratique_db
          property: connectionString

databases:
  - name: pratique_db
    plan: free
